# Writes the notes of a release (Markdown), see "Versions" in docs/technical.md:
#
#   ## <title of the pull request merged into main>
#   <its description>
#   ---
#   Rev. <n>: why the earlier attempts of this run failed (only after a re-run)
#   which installer to download, and the changes since the previous release
#
# Without a pull request (released by hand) the notes generated by GitHub take the place of the first part.
param(
    [Parameter(Mandatory)] [string]$Version,
    [Parameter(Mandatory)] [string]$OutFile
)
$ErrorActionPreference = 'Stop'
$repo = $env:GITHUB_REPOSITORY
$tag = "v$Version"

function Invoke-GhApi([string]$path) {
    $json = gh api $path
    if ($LASTEXITCODE -ne 0) { throw "gh api $path failed" }
    return $json | ConvertFrom-Json
}

$lines = New-Object System.Collections.Generic.List[string]

$pr = @(Invoke-GhApi "repos/$repo/commits/$env:GITHUB_SHA/pulls") |
    Where-Object { $_.merged_at -and $_.base.ref -eq 'main' } | Select-Object -First 1
if ($pr) {
    $lines.Add("## $($pr.title)")
    if ($pr.body) {
        $lines.Add('')
        $lines.Add($pr.body.Trim())
    }
}
else {
    $generated = gh api "repos/$repo/releases/generate-notes" -f tag_name=$tag -f target_commitish=$env:GITHUB_SHA --jq .body
    if ($LASTEXITCODE -ne 0) { throw 'Cannot generate the release notes' }
    $lines.Add(($generated -join "`n").Trim())
}
$lines.Add('')
$lines.Add('---')
$lines.Add('')

# This run was re-run: say why the earlier attempts failed
$attempt = [int]$env:GITHUB_RUN_ATTEMPT
if ($attempt -gt 1) {
    $lines.Add("Rev. $($attempt - 1):")
    for ($n = 1; $n -lt $attempt; $n++) {
        $job = @((Invoke-GhApi "repos/$repo/actions/runs/$env:GITHUB_RUN_ID/attempts/$n/jobs").jobs)[0]
        $step = $job.steps | Where-Object conclusion -eq 'failure' | Select-Object -First 1
        if (-not $step) {
            $lines.Add("- previous attempt (${n}): $($job.conclusion)")
            continue
        }
        # The job's error annotations, without GitHub's generic "Process completed with exit code" line
        $errors = @(Invoke-GhApi "repos/$repo/check-runs/$($job.id)/annotations") |
            Where-Object annotation_level -eq 'failure' |
            ForEach-Object { ($_.message -split "`n")[0].Trim() } |
            Where-Object { $_ -and $_ -notmatch '^Process completed with exit code' }
        $why = if ($errors) { ': ' + @($errors)[0] } else { '' }
        $lines.Add("- previous attempt ($n) failed at ""$($step.name)""$why")
    }
    $lines.Add('')
}

$lines.Add('Download **one** installer: `WinHotCorner-Full-' + $Version + '-setup.exe` (hot corner and control panel, recommended) or `WinHotCorner-HotCornerOnly-' + $Version + '-setup.exe` (hot corner only).')

$previous = git tag --list 'v*' |
    Where-Object { $_ -match '^v\d+\.\d+\.\d+$' -and $_ -ne $tag } |
    Sort-Object { [version]$_.Substring(1) } | Select-Object -Last 1
if ($previous) {
    $lines.Add('')
    $lines.Add("**Full Changelog**: https://github.com/$repo/compare/$previous...$tag")
}

Set-Content -Path $OutFile -Value ($lines -join "`n") -Encoding utf8
